# Generated by Django 4.1.5 on 2023-01-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Snacks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("totalQuantity", models.IntegerField()),
                ("usedQuantity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="VendingMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("balance", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField()),
                (
                    "snacks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vending.snacks"
                    ),
                ),
                (
                    "vendingMachine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vending.vendingmachine",
                    ),
                ),
            ],
        ),
    ]
