# Generated by Django 4.1.5 on 2023-01-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendingmachine",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
