# Generated by Django 4.1.5 on 2023-01-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snacks",
            old_name="usedQuantity",
            new_name="availableQuantity",
        ),
    ]
