# Generated by Django 4.1.5 on 2023-01-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0002_rename_usedquantity_snacks_availablequantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendingmachine",
            name="balance",
        ),
    ]
