# Generated by Django 4.1.5 on 2023-01-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0002_vendingmachine_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snacks",
            name="available",
        ),
    ]
